### ISSUE TITLE
Existing User: Buy Wizard does not ask user for Wall of Coins password.

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#15]
When specifying an existing phone number, we are not obtaining the existing user's WOC password to register a new device.

Request: ```POST /api/v1/auth/+12397776832/authorize/ HTTP/1.1" 400```

Expected results when this request gets status response 400:
1. Give a message to the user, "It appears that you already have a [Wall of Coins] user account!" [Wall of Coins] will link to https://wallofcoins.com
2. Ask the user, "Input your Wall of Coins password below:" followed by a Password Input on the next line.
3. The next line will say in smaller text, "(your password is only sent to Wall of Coins)"
4. Provide a web link at the bottom of the page, "Forgot your Wall of Coins password? [Reset] it here." -- and have the [Reset] link go to: https://wallofcoins.com/forgotPassword/
5. When the user inputs their password, then attempt to login using the authorize endpoint. When you have logged in, grab the token from the API response.
6. With the token, you will create a new device using the /api/v1/device(s??) endpoint.
7. After creating the new device, you will need to use /api/v1/auth/{phone number}/authorize/ to get a token using the device code instead of the password.
8. Use the new token in the HEADER to create this hold via /api/v1/holds

![screenshot_20180116-002850](https://user-images.githubusercontent.com/368863/34973238-aaf8fec0-fa54-11e7-9e8a-0180400ad369.png)

**Comment by jaydeep82** [comment]
@rgenito This issue has been fixed.

**Comment by rgenito** [comment]
Perfect! :) I have a few change requests, and then this issue will be closed:

- [ ] Change the first sentence to: "You are already signed up for [Wall of Coins]!"
- [ ] Change the password sentence to: "(For security, your password will not be saved.)"
- [ ] Change the "Forgot your Wall of...Reset it here" to a button that says, "FORGOT PASSWORD". When the end user presses this button, the same action will happen;.

**Comment by jaydeep82** [comment]
@rgenito all three points have been fixed.
