### ISSUE TITLE
Buy Summary page is redundant when there are multiple orders

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#16]
To create this situation, create at least 2 orders for your user account. Then, refer to the screen shot to understand what changes need to take place.

- [x] Move the message, "You're ordering X.YYYYZZZZ Dash" to be directly under "Cash to Deposit:", and change the message to say, "Total Dash: X.YYYYZZZZ (X,YYY,YZZ.ZZ dots)"
- [x] For the text that is inside the RED SQUARE, remove that message part when the order status is NOT "WD".

![screenshot_20180116-005315](https://user-images.githubusercontent.com/368863/34973973-90b2d92e-fa58-11e7-9492-f335510c89ea.jpg)

**Comment by jaydeep82** [comment]
@rgenito this issue has been fixed.

**Comment by jaydeep82** [comment]
@rgenito could you assist what is remaining in this issue?

**Comment by rgenito** [comment]
Due to errors, I am unable to QA test this until a fix with the other issues.

**Comment by jaydeep82** [comment]
@rgenito what should we do when user close the app without deposit payment? In this scenario, when user open the app again, they see order list without deposit and cancel order button. Sometime its shows only single record details without signout button and sometime it shows order manager list with signout button.
