### ISSUE TITLE
App crashes when accessing the Buy Summary

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#18]
Here is how I reached this problem:

1. Press the "load your new Dash Wallet" link from the main screen.
2. During the Buy Wizard, enter an existing WOC account so that you are prompted to input your password.
3. Create an Order ("capture the hold" until you see the Buy Instructions)
4. Hit the back button to go back to the main transactions screen.
5. Press the menu button (top-left)
6. Press "Buy Dash with Cash"

The app then crashes.

**Comment by rgenito** [comment]
Good! looks like it is not crashing. NOW...

After doing steps 1-6, the deposit finished and cancel buttons are MISSING. The user still needs those buttons :)
