### ISSUE TITLE
Buy Summary page does not display Buying Instructions

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#21]
We have a separate UI template for the "Buying Instructions", and this UI template includes the end user's instructions to pay for their order. Additionally, this includes a "Deposit Finished" and "Cancel Order" button.

Here are problems with our current Buy Summary page:
- [x] For each order with status "WD", we must display the Buying Instructions UI template. Therefore, each order with status == "WD" will have the Finished/Cancel button.
- [x] The Buying Instructions template (even when this template is present within the Buy Summary UI template), must display the "DEPOSIT FINISHED" and "CANCEL ORDER" buttons for orders.status == "WD".

**Comment by jaydeep82** [comment]
@rgenito this issue has been fixed.
