### ISSUE TITLE
TestNet: new Order gives me unexpected Buying Instructions

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#23]
1. uninstall testnet
2. reinstall testnet
3. Go to Buying Wizard from Transactions Page link.
4. "Find my location" -> approve to use location
5. Search for $50 to spend. Click to get Offers.
6. Select first offer (Wells Fargo)
7. No email, and specify phone: 2397776832
8. Input password "abc123"

Here are the immediate problems I noticed: **Then, I do not see the view to input my Purchase Code! I am immediately brought to the Buying Instructions screen.**

On the buying instructions screen, furthermore I see...

1. Deposit Due is 0 minutes and 0 seconds.
2. The "deposit finished" and "cancel order" buttons were visible.
3. When I looked at the Django backend of my development instance, I see that a new Hold and a new Order were both NEVER created for my phone number. However, I did see the creation of a Discovery Input.

I do not know which Order you were showing me. Was there an API error you did not catch? From an error, did you fall back on showing me my last order?

The expected response is:
1. The Hold is created and captured and a new Order is created on the web admin page.
2. I see the Buying Instructions for my new order.
3. Or, I receive an error when attempting to create the Hold.

**Comment by jaydeep82** [comment]
>  Then, I do not see the view to input my Purchase Code! I am immediately brought to the Buying Instructions screen.

As we've implemented the functionality of automatically submit the form after 5th character enter in purchase code textbox, TestNet app get the verification code from api and set it in purchase code text box. so it do not show the purchase code screen.

Should we cancel the order when deposit due time out ( 0 minutes and 0 seconds )? 

For number +12397776832, we're getting more than 270+ orders from api. Only 10 have account number and rest have null.

**Comment by rgenito** [comment]
Oooooh I understand now :)

As you asked earlier, we do not need to cancel the user when the time of deposit due has been reached: the API automatically cancels the order.

@jaydeep82 what's your status on this?

**Comment by rgenito** [comment]
I can no-longer duplicate this bug...awesome :)
