### ISSUE TITLE
Buying Summary needs to show Order statuses for non "WD" orders

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#24]
This is missing from the specifications, and it must be included.

For each previous order listed on the "Buying Summary" page, put the Status underneath the "Cash to Deposit" label. Here are the specifics:

1. The label will be: "Status: {{order.status}}"
2. The statuses are listed as codes. For example, "WD", "WDV", "RERR", "DERR", etc. You will not show the user the status code; instead, you will give the user a different label for the status codes.

The status codes and their labels will be in the next comment.

![screenshot_20180125-111219](https://user-images.githubusercontent.com/368863/35398804-ceab634e-01c0-11e8-9c85-0158f5d5ca06.jpg)

**Comment by rgenito** [comment]
These are the codes in english...

    ('WD', __('Waiting Deposit')),
    ('WDV', __('Waiting Deposit Verification')),
    ('RERR', __('Issue w/ Receipt')),
    ('DERR', __('Issue with Deposit')),
    ('RSD', __('Reserved for Deposit')),
    ('RMIT', __('Remit Address Missing')),
    ('UCRV', __('Under Review')),
    ('PAYP', __('Done - Pending Delivery')),
    ('SENT', __('Done - Units Delivered')),

**Comment by jaydeep82** [comment]
@rgenito this issue has been fixed.
