### ISSUE TITLE
Need Instructions for Customer Support

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#25]
On the Buying Summary page, we need a Support Panel. Put this Support Panel above the "Sign Out" panel, and put the following text and buttons on the panel...

(if customer is in the USA)
    Call (866) 841-2646 for help.
(else if customer is outside of the USA)
    Call +1 (217) 672-6467 for help.
(end if)
    Help is also available on the website.

Then put a grey button that says, "WALLOFCOINS.COM", and when the user clicks this button, a new browser window will bring up the website https://wallofcoins.com

**Comment by jaydeep82** [comment]
@rgenito this issue has been fixed.
