### ISSUE TITLE
Buy Summary page: order.accountNumber JSON must render PayFields

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#27]
when order.accountName is blank, then order.accountNumber will always include JSON. This JSON means that the accountNumber is much more complex and will contain multiple "payfields". These need to be rendered similar to how they are done on the Buying Instructions template.

Read the annotation on the attached screen shot for more information.

![screenshot_20180129-104142](https://user-images.githubusercontent.com/368863/35519192-89c4e498-04e1-11e8-9323-c67d54350299.jpg)

**Comment by jaydeep82** [comment]
@rgenito I've fixed this issue. I think now first we must re-fragmentise the code of buy dash fragment java file as it is now become very complex and taking lots of time to do small changes. I also found other issues like status, payment amount are not coming after order purchase (capture hold).

**Comment by rgenito** [comment]
@jaydeep82 the Buying Wizard needs to be re-created, basically. You took over code from a previous developer who did not have the experience to do what was necessary. We will talk of that next :)
