### ISSUE TITLE
Old Buying Instructions appear with new order

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#28]
To recreate this issue:

1. Download a fresh install of the app.
2. Create an order with some phone number.
3. Mark that order as "DEPOSIT FINISHED".
4. Go to the Buy Summary page.
5. Press "SIGN OUT"
6. Create a new order WITH A DIFFERENT PHONE NUMBER.
7. When you get to the Buying Instructions, you will find instructions for the LAST user's order instead of getting the new instructions!

Our admin panel can be seen below...

![select_order_to_change___django_site_admin](https://user-images.githubusercontent.com/368863/35520098-087b1a30-04e4-11e8-82bb-9f63c1b71d72.jpg)

**Comment by jaydeep82** [comment]
@rgenito I'm not able to reproduce this issue now.
