### ISSUE TITLE
Order status "RSD" has extra apostrophe

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#30]
When an order's status is "RSD", the Buy Summary page lists it like the following...

```
Cash to Deposit: $50.00
Status: Reserved for Deposit'
Total Dash: 4.60795231 (4,607,952.31 dots)
```

Remove the ```'``` from "Reserved for Deposit".

**Comment by jaydeep82** [comment]
@rgenito this point has been fixed.
