### ISSUE TITLE
Support NDK for native-scrypt & native-x11

### ISSUE THREAD

**Issue by jaydeep82** [genitrust/dash-wallet#33]
Developer will face issue for include Header files for Native Code.
/home/felix/workspace/dash-wallet/native-scrypt/src/scrypt_jni.c:3:19: fatal error: errno.h: No such file or directory
 #include <errno.h>
                   ^
compilation terminated.

**Comment by jaydeep82** [comment]
Issue fix by using android-ndk-r15c-windows-x86_64

**Comment by HashEngineering** [comment]
This issue has been encountered before:
https://github.com/bitcoin-wallet/bitcoin-wallet/issues/485
https://github.com/HashEngineering/dash-wallet/issues/52
