### ISSUE TITLE
Bank Logos and Icons: use the non-HQ value specified in response

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#35]
For all API responses that contain the banking center's (or payment destination's) banking logo and icon, we will now grab these response properties to use as the logo/icon image links:

```
bankLogo
bankIcon
```

Before we were grabbing the values from ```bankLogoHq``` and ```bankIconHq```, which will be deprecated.

**Comment by jaydeep82** [comment]
@rgenito this point has been fixed.
