### ISSUE TITLE
Buying Wizard "incremented offers"

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#36]
When they Discovery Input offers object contains...

```
{
  . . .
  incremented: true
}
```

This means that the search amount (for example "$25") was not available for all offers--some offers that are available REQUIRE the end user (buyer) to deposit slightly more than $25. This is what is meant by the term ```incremented```. Here is the actual example from the API call:

![woc_development_new_user_creates_order_search_for__25_worth_of_dash_-_restlet_client](https://user-images.githubusercontent.com/368863/36052754-f87f1e88-0dbc-11e8-8151-9a93f9de2905.jpg)

![woc_development_new_user_creates_order_get_search_results_-_restlet_client](https://user-images.githubusercontent.com/368863/36052762-002fefea-0dbd-11e8-88f3-16a0aa4dbd68.jpg)

Currently, your Offers screen for this project renders the following:

![screenshot_20180209-155724](https://user-images.githubusercontent.com/368863/36052779-14248f60-0dbd-11e8-9ba5-1b22d9b2387f.jpg)

You must update this screen to do the following **when ```incremented: true```**!!

- [x] Instead of saying, "Below are offers for $25.02. You must click....Cash Payment center", the message needs to state, "Below are offers for at least $25. You must click......Cash Payment center." Notice that the word "at least" is inserted, and the dollar amount is equal to their search amount.
- [x] Underneath the ORDER button must be the order amount in this format: "Pay ${offer amount}". For example, Figure A will have underneath ORDER button the label "Pay $25.02"; Figure B will have "Pay $25"; and Figure C will have "Pay $25".
- [x] When ```incremented: false```, you will continue to display the Screen exactly as you already display it. You must preserve the current implementation state of the Offers Screen when ```incremented: false```.
- [x] Furthermore, you will also: update the WallofCoins-README.md (in basecamp AND in this project repository) to educate the 3rd party developer on how to respond depending on the "incremented" boolean value.

**Comment by jaydeep82** [comment]
@rgenito this point has been implemented.

**Comment by rgenito** [comment]
@jaydeep82 you still have work to do:

- [ ] when "incremented" is false, you say "Below are offers for $...", when "incremented" is true, you say "below are offers for at least $..." -- your message will be different depending on the value of incremented!

**Comment by jaydeep82** [comment]
@rgenito this point has been fixed.
