### ISSUE TITLE
"Device ID required" error when attempting to capture hold with number +12397777007

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#37]
To recreate this issue, start with a fresh install and attempt to BUY with the phone number +12397777007.

![screenshot_20180209-194701](https://user-images.githubusercontent.com/368863/36056396-2761d4ce-0dd2-11e8-8e12-f42985fe1087.png)

**Comment by jaydeep82** [comment]
@rgenito this issue has been fixed.

**Comment by rgenito** [comment]
I follow these instructions exactly:

1. start with a fresh install
2. attempt to BUY with the phone number +12397777007.

And then I get an error and I see this screen....

![screenshot_20180219-170422](https://user-images.githubusercontent.com/368863/36399155-99a46948-1598-11e8-8351-3da647d57a8a.png)

**Comment by jaydeep82** [comment]
@rgenito this point has been fixed.

**Comment by jaydeep82** [comment]
Currently for +12397777007 it is working correctly. I've created #47.
