### ISSUE TITLE
Buy Summary: "WDV" status orders still show the account details

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#38]
To recreate this issue:

1. start with a fresh install
2. Create an order, and use a phone number that does not exist in our system.
3. Click the Deposit Finished button, then click to Confirm

When you are brought back to the Buy Summary page, you can still see the values for the "Name on Account" and "Account #". If the advertisement's banking options uses Pay Fields JSON.

**Requirement:** when the order status is WDV, you will not show any of these account details.

**Comment by jaydeep82** [comment]
@rgenito this issue has been fixed.

**Comment by rgenito** [comment]
@jaydeep82 this issue has not been fixed. FOLLOW THE PROCEDURE I WROTE ABOVE **EXACTLY**.

![screenshot_20180219-172023](https://user-images.githubusercontent.com/368863/36399921-19bbf508-159c-11e8-94f4-4118ccc52e58.png)

**Comment by jaydeep82** [comment]
@rgenito Do we also need to hide Pay Fields JSON when the order status is WDV ?. 
1) Currently I have updated hide "Name on Account" and "Account #".
2)

**Comment by rgenito** [comment]
@jaydeep82 yes, you need to also hide the Pay Fields JSON when the order is WDV. The payfields JSON is exactly the same as the order's payment destinations account/account-number.

Good call and good job handling both of these :)
