### ISSUE TITLE
Buy Summary Updates

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#39]
- [x] BUY MORE DASH button must be in the yellow color with blue text (just like SIGN OUT button currently is)
- [x] The Support Panel will be directly under "WD"-status orders.
- [x] The SIGN OUT Panel will be directly under the Support Panel (just as it is now)
- [x] The SIGN OUT button will be grey with black text, like the WALLOFCOINS.COM button.
- [x] Under the SIGN OUT panel will be big, centered text saying, "Previous Orders"
- [x] Under the big "Order History" text will be every order that is NOT "WD" status.

**NOTE:** Currently, I see "RERR" status ("Issue with Receipt") orders that are placed ABOVE the Support Panel ... when they should be underneath the Order History section. Therefore...

- [x] ...when the end user first goes to the Buy Summary Screen: you need to be updating the WD orders and moving them to the "Order History"! To update an order with WD status, use the order id and call ```GET /api/v1/orders/{id}/```

**Comment by jaydeep82** [comment]
Query : 1) Underneath the BUY MORE DASH button will be all orders with status "WD". 
  >>  We are currently show "BUY MORE DASH" button when there is not record with order status "WD". Let me know if we want to update this condition.

**Comment by rgenito** [comment]
@jaydeep82 looks good!
