### ISSUE TITLE
New device is created for every Hold that is created

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#4]
To replicate this bug, do the following:

1. Fresh install and open the app
2. Press the hamburger menu icon on the top-left
3. Press Button: Find My Location
4. Type in 0.2 Dash
5. Press Button: Get Offers
6. Press Button "ORDER" for the offer that pops up.
7. Press Button: "Confirm Purchase Code"
8. Press Button: "Deposit Finished"
9. Press Button: "OK"
10. Go to the Wall of Coins dev server's "admin" section, and click Devices. You will see a new device created. Write down the numeric device ID.
11. Go back to the Android app and press the button: "BUY MORE DASH!"
12. Press: find my location, type in 0.1 DASH, press "GET OFFERS"
13. Press button "ORDER" for the first offer that comes up.
14. Press CONFIRM PURCHASE CODE, press DEPOSIT FINISHED, press OK.
15. Go back to the Wall of Coins dev server's admin, and you'll see that a new device was created.

This is happening because you are creating a new device when you do POST /api/v1/holds by specifying the parameters <code>deviceName</code> and <code>deviceCode</code>. Once the user already has a device, you must call POST /api/v1/holds with the <code>X-Coins-Api-Token</code> header and *without* the <code>deviceName</code> and <code>deviceCode</code>.

When you first create a device and receive its X-Coins-Api-Token from the server response, you need to save that device's <code>phone</code> number and <code>deviceCode</code> locally so that you can use it for authentication via /api/v1/auth in the future.

* Problem: A new device is created for every Hold that is created.
* Solution: Only create the device once, save the deviceCode locally, and use that to authenticate the device for future orders.
* Benefit: We can better track the user's device installations.

**Comment by viral85** [comment]
The issue was resolved in the last build...
Can you please test it here: https://basecamp.com/2036174/projects/14470579/todos/336868383

**Comment by rgenito** [comment]
I have confirmed on TESTNET build that this is resolved.
