### ISSUE TITLE
Unknown status "Waiting Done - Units Delivered"

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#40]
If you have any questions, ask here. I don't know what status this is, and it is not in the specifications I gave you.

![feb9-screenshot_20180209-160010](https://user-images.githubusercontent.com/368863/36056838-f084232c-0dd5-11e8-9cf4-a633618d2940.jpg)

**Comment by jaydeep82** [comment]
Issue fixed with update of 
Status: Done - Units Delivered for (Status code : SENT)
