### ISSUE TITLE
Existing User Password Prompt updates

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#41]
- [x] implement X icon and behavior to close out the window (returning to previous screen)
- [x] You are -> "You're"
- [x] remove "!" from the sentence.
- [x] Change message to "Input your password below:"
- [x] Replace "(For security, your password will not be saved.)" to "Your password is transmitted securely." -- notice that I removed the ()'s.

![feb9-screenshot_20180209-160400](https://user-images.githubusercontent.com/368863/36056940-c707dab0-0dd6-11e8-8221-74ac70f0f055.jpg)

**Comment by jaydeep82** [comment]
@rgenito this point has been implemented.
