### ISSUE TITLE
Existing User: unable to create order

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#42]
An existing WOC user is unable to create an order. Follow this process:

1. Open a fresh install of the app.
2. Go to the Buy Wizard
3. Attempt to create an order with the number +12397776832
4. When prompted, use the password "abc123".

The app will then show the loading status animation for a while, and finally the app will bring you back to the beginning of the Buy Wizard. Also, when you exit the app and then go back to the main screen, going back to the Buy Wizard will show the Buy Summary screen for this user.

We need the new order to be created by first creating the hold and prompting the user to capture the hold. By the way, this ONLY happens with the +12397776832 phone number. Other phone numbers--ones that have significantly less orders--will not have this behavior.

**Comment by jaydeep82** [comment]
@rgenito I've fixed this issue.

**Comment by jaydeep82** [comment]
@rgenito We are waiting for update on method for get holds on development server.
