### ISSUE TITLE
Find My Location button should only be pressed once?

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#43]
When I get to the buying wizard and I have a choice between "Find My Location" and "No Thanks", I have to do the following to get my location tracked:

1. Press "Find My Location"
2. Press "OK" or "Yes" to agree to share my location
3. Press "Find My Location" again.
4. I now see the "I'm looking to spend..." area.

Here's how we prefer to do this for the user experience...

1. Press "Find My Location"
2. Press "OK" or "Yes" to agree to share my location
3. I now see the "I'm looking to spend..." area.

Can we do this?

**Comment by jaydeep82** [comment]
@rgenito this big has been fixed.
