### ISSUE TITLE
Update Message when end user confirms DEPOSIT FINISHED

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#44]
Update this message to say:

"Thank you for making the payment! Once Wall of Coins verifies the payment, you will receive your Dash!"

![screenshot_20180219-165951](https://user-images.githubusercontent.com/368863/36399976-4f1f44b6-159c-11e8-8233-9987f7f90d0f.png)

**Comment by jaydeep82** [comment]
@rgenito this point has been fixed.
