### ISSUE TITLE
Buying Wizard User Experience enhancement

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#45]
@sujalBandhara please see that this is finished with Jaydeep.

Use the developer instance.

+19413767746

1. get a fresh install.
2. press "BUY DASH WITH CASH" from the main page.
3. press "FIND MY LOCATION"
4. $500 for "i'm looking to spend". Press "GET OFFERS".
5. Select the WELLS FARGO option by pressing ORDER next to Wells Fargo
6. press "do not send me email"
7. Use the phone number (USA) 941 376 7746, press NEXT
8. input password "asdf1234", press LOGIN
9. press CANCEL ORDER.
10. press OK to confirm that you want to CANCEL the order.
11. Press the back button (<-) on the top-left of the page.

OBSERVATION: why are you bringing the user back to the page that has the buttons DEPOSIT FINISHED and CANCEL ORDER? **Requirements:** bring the user back to the BEGINNING (as if they pressed "BUY DASH WITH CASH", which will either bring them to Buy Summary or Buy Wizard).

12. Press the back button (<-) on the top-left of the page AGAIN.

(sometimes the app will crash here if you are doing this fast enough...)

13. Press the BUY DASH WITH CASH button.
14. Scroll down, and you will now see (with our current data) that there is a WDV order immediately after ORDER HISTORY.

This WDV order is erroneously showing. **Requirement:** do not show the payment details for this WDV order.

**Comment by jaydeep82** [comment]
@rgenito this point has been fixed.

**Comment by rgenito** [comment]
Nice :) very happy to see this!
