### ISSUE TITLE
Unable to create new order with brand new customer

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#46]
Here is what I do, including the observations:

1. Search for $60 - discovery input is created w/ associated publisher.
2. Get offers.
3. Create Hold w/ an Auth's phone number that has never been used with WOC.

I get the error "You can only have 1 active hold at a time".

* The Auth was created.
* The discovery input object that was created now has the Auth property set.
* The Hold was also created, and it is Active and waiting to be captured.
* The Buy Summary (or Buy Wizard) is a completely blank view.

**Comment by jaydeep82** [comment]
@rgenito this bug has been fixed.
