### ISSUE TITLE
Buy Wizard: API creates the same HOLD twice for a first time user.

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#49]
I am observing that the first time user always has 2 holds created:

* 1st hold is created.
* then that 1st hold is cancelled.
* then another hold (for the same offer) is created.

Something is going wrong, and I am expecting to see that only ONE hold is created for the user's offer.

![double-holds-select_hold_to_change___django_site_admin](https://user-images.githubusercontent.com/368863/36462630-8b833934-1692-11e8-88c7-c0fcfb26a04e.jpg)

**Comment by jaydeep82** [comment]
@rgenito this bug has been fixed.
