### ISSUE TITLE
Buy Wizard: no message for wrong password input

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#51]
To reproduce this issue, create an order with an existing user who has a WOC password.

When you are asked for the password, input the wrong password.

NOTICE: you are brought back to the phone # input screen.

HERE'S WHAT NEEDS TO HAPPEN after the API call is not successful with the given password:
* Alert the user: "Unable to Sign In. Check that you input your right phone number and re-try your password."
* Allow the user to press OK to dismiss the alert message.
* Bring the user back to the phone number input field.

**Comment by jaydeep82** [comment]
@rgenito this bug has been fixed.

**Comment by rgenito** [comment]
When I input the correct password, I am brought to a blank screen. Are you reading the status codes properly? Try again.

**Comment by rgenito** [comment]
Strange, I am able to login with the MainNet app, but not for TestNet.

**Comment by jaydeep82** [comment]
@rgenito this issue has been fixed.

https://github.com/genitrust/dash-wallet/commit/fdcc5173ec27964955d46b68755e053f6769b50a
