### ISSUE TITLE
Many "leaks"

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#52]
Are you aware of the software leaks?

Check out the screen shot. This is happening for both TestNet build and the MainNet build.

![screenshot_20180220-235711](https://user-images.githubusercontent.com/368863/36463781-04e989de-169a-11e8-91bc-5e5c1619b71d.png)

**Comment by jaydeep82** [comment]
@rgenito I've fixed many leaks. I will keep watching it and fix it.

**Comment by rgenito** [comment]
@jaydeep82 how do i know that you have fixed them? You need to supply commit hashes as reference. Please provide commit and (if the leak fix was committed with many other changes) the line number.

**Comment by rgenito** [comment]
For example, I also get a memory leak on MainNet when i 1) create an order with existing phone number (+12397776832), 2) cancel the order, then click Back (<-), then press the BUY DASH WITH CASH button from the main screen.

I will see the Buy Summary page; however, I will also see the warning about the memory leak.

**Comment by jaydeep82** [comment]
@rgenito 
https://github.com/genitrust/dash-wallet/commit/fdcc5173ec27964955d46b68755e053f6769b50a

Following are lines where I've fixed the leaks today:
Line numbers of BuyDashFragment : 207, 209, 291

I will keep monitoring app for leaks.

**Comment by rgenito** [comment]
I haven't found any more leaks since! :)
