### ISSUE TITLE
Unable to log out of a user with no orders.

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#54]
I am unable to log out of a user that has no orders. Here's how I produced this bug:

1. Create an order with a brand new user.
2. Cancel that order.

You are then brought back to the BUY DASH WITH CASH page. However, there is no option for me to sign out of this phone number.

**REQUIREMENTS:**

When the user is logged in and viewing the beginning of the Buy Wizard (the part w/ FIND MY LOCATION and NO THANKS buttons), you are to display the Sign Out Panel at the bottom of that screen.

![screenshot_20180221-001217](https://user-images.githubusercontent.com/368863/36464150-2d240544-169c-11e8-9a98-8d97d64b4d11.jpg)

**Comment by jaydeep82** [comment]
@rgenito this point has been implemented.
