### ISSUE TITLE
Existing Auth (with WOC password) will not have API device verified

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#55]
When capturing holds, I see that the Auth's device will have verified=True. However, this is not the case with Device's owned by Auths who have the ```password``` property set.

Based on Andrew's response, here's what's going on:
* you are using the auth token in X-Coins-Api-Token to capture the hold, you are not using the Device token.

What you need to do after you receive status 401 from POST /api/v1/holds/:
* create device using the Auth's token
* login w/ new device id/code to get the Device token
* create the Hold w/ the new Device token in X-Coins-Api-Token
* procede to save the device id and code locally, then capture the hold, then display order instructions, etc. etc.

![device-not-verified-select_device_to_change___django_site_admin](https://user-images.githubusercontent.com/368863/36465333-8cf76014-16a2-11e8-8773-0f5d8aeb5fa8.jpg)

**Comment by jaydeep82** [comment]
@rgenito this issue has been fixed.

**Comment by rgenito** [comment]
@jaydeep82 i am unable to QA this. I'm blocked by https://github.com/genitrust/dash-wallet/issues/51
