### ISSUE TITLE
Location preferences must send Geo Coords

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#56]
When the user wishes to share their location, have Android's SDK send to POST /api/v1/discoveryInputs the geo coordinates (latitude and longitude).

![change_discovery_input___django_site_admin](https://user-images.githubusercontent.com/368863/36643426-155a8b38-1a19-11e8-874f-5a3cb8fe3837.jpg)

**Comment by jaydeep82** [comment]
As @sujalBandhara also need to do in iOS, I'm adding him here.

**Comment by sujalBandhara** [comment]
HI @rgenito I have fixed this in https://github.com/genitrust/dashwallet-ios/commit/e96d45f06c045f31ed138d072e58a201f984c576 

I have also update ReadMe File regarding this.

**Comment by jaydeep82** [comment]
@rgenito this point has been fixed.

https://github.com/genitrust/dash-wallet/commit/fdcc5173ec27964955d46b68755e053f6769b50a
