### ISSUE TITLE
Double Discovery Input searches are sent.

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#58]
To recreate this bug:

1. Use fresh install of MainNet app (i did not test this on TestNet, but please reproduce and resolve this bug on TestNet if possible!!!)
2. Use an existing phone # that contains a WOC password (ie +12397776832)
3. Create an order.
4. Notice on the Admin backend that your app will have made the Discovery Input call twice AND create 2 new wallet addresses (instead of 1).

Solution: only call Discovery Input and wallet address once per Order process.

@sujalBandhara please make sure iOS also does not have this behavior.

![double-discovery_select_discovery_input_to_change___django_site_admin](https://user-images.githubusercontent.com/368863/36644190-9a9a9e04-1a24-11e8-88fc-ae79d55930fc.jpg)

![screenshot_20180225-120623](https://user-images.githubusercontent.com/368863/36644192-aab39d22-1a24-11e8-96be-db4fa3b68ad5.png)

**Comment by sujalBandhara** [comment]
@rgenito In iPhone Discovery Input is call one time. I checked in TestNET

**Comment by jaydeep82** [comment]
@rgenito this point has been fixed.

https://github.com/genitrust/dash-wallet/commit/fdcc5173ec27964955d46b68755e053f6769b50a

**Comment by rgenito** [comment]
@jaydeep82 i am so happy :)
