### ISSUE TITLE
Buying instructions use the word "null" to describe cash.

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#6]
The word "null" is popping up everywhere that we have Buying Instructions. Remove the variable entirely (so that the word "null" does not show up. Preferably, find a way to track which fiat currency they are using and use the word "USD" instead of "null"!

**Comment by viral85** [comment]
I need currency in order list API, create hold API and capture hold.

**Comment by rgenito** [comment]
This issue still needs to be resolved. Anything but "null" is acceptable! :)

**Comment by viral85** [comment]
> Anything but "null" is acceptable! 
I am not getting...
Should I check null or I have to let it as it is.

**Comment by rgenito** [comment]
to be clear.... print the variable. if the value is null, do not print "null", print a blank line instead!

**Comment by rgenito** [comment]
ehh, just remove the variable. just say "...you must deposit cash..."

**Comment by rgenito** [comment]
@jaydeep82 we have buying instructions that tell the end user "you must deposit {{ variable here }} cash" ... for this task, you will remove "{{ variable here }}".

**Comment by jaydeep82** [comment]
@rgenito I think this message is already fixed by the previous developer in wallofcoins-buying-wizard branch. A lastest instruction message is "You must deposit cash at the above Payment Center. Additional fees may apply. Paying in another method other than cash may delay your order."
