### ISSUE TITLE
"You are not authorized to post a hold"

### ISSUE THREAD

**Issue by robertgenito** [genitrust/dash-wallet#9]
I get this error on the testnet app connecting to the dev server, using my phone # +1 239 777 6832 :\

**Comment by viral85** [comment]
The error message getting from API with Error Code 403. 
the case is there is no API and user type is showing phone and device both.
So I am requesting to create hold with deviceCode.
As one has created the device previously with old apk, it may be the chance that device code is different than previous one. 

It's the case that I don't have auth token and don't have older device code as well.

Please guide me for such situation.

**Comment by rgenito** [comment]
implement what you were supposed to implement previously: if you cannot log in, create a device!

**Comment by viral85** [comment]
Ok, I will create device and Update you with that on monday

**Comment by jaydeep82** [comment]
@rgenito this issue has been fixed for TestNet.
